version: '3'
services:
  offshore-proxy-server:
    build:
      context: .
      dockerfile: Dockerfile-offshore-server
    container_name: offshore-proxy-server
    ports:
      - "9090:9090"
    dns:
      - 8.8.8.8

  ship-proxy-client:
    build:
      context: .
      dockerfile: Dockerfile-ship-proxy
    container_name: ship-proxy-client
    ports:
      - "8080:8080"
    depends_on:
      - offshore-proxy-server
    command: offshore-proxy-server 9090
    dns:
      - 8.8.8.8